apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: preprod

replicas:
  - name: www
    count: 4

images:
  - name: nginx
    newtag: "1.26"

configMapGenerator:
  - name: www
    envs:
      - www.env
