apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-http
  name: hello-http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-http
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-http
    spec:
      containers:
      - image: bob2606/hello-http:0.8.27
        name: hello-http
        envFrom:
          - configMapRef:
              name: hello-http
        readinessProbe:
          httpGet:
            path: /helathz
            port: 80
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 15
          failureThreshold: 2
