apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: load
  name: load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: load
    spec:
      containers:
      - image: busybox
        name: busybox
        resources:
          limits:
            cpu: 250m
        command:
          - sh
          - -c
          - |
            while :
            do
              :
            done
status: {}
