apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: load
  name: load
spec:
  containers:
  - image: busybox:1.28
    name: load
    resources: {}
    command:
      - sh
      - -c
      - |
        while :
        do
          :
        done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
