apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        env:
          - name: FORMATION
            value: Kubernetes
          - name: PODIPD
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: JRS
            valueFrom:
              configMapKeyRef:
                name: www
                key: JOURS
        envFrom:
          - configMapRef:
              name: www
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 4
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 10
          failureThreshold: 2
        volumeMounts:
          - name: data
            mountPath: /usr/share/nginx/html

      volumes:
        - name: data
          hostPath:
            path: /data
            type: Directory
