apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: allowall-bob
  namespace: stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allowall
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob
