apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: dev-

replicas:
  - name: www
    count: 2

images:
  - name: nginx
    newtag: "1.27"

configMapGenerator:
  - name: www
    envs:
      - www.env
