apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: prod

replicas:
  - name: www
    count: 10

images:
  - name: nginx
    newtag: "1.24"

configMapGenerator:
  - name: www
    envs:
      - www.env
